# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-04 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odpowiedz', models.CharField(max_length=200)),
                ('glosy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_pytania', models.CharField(max_length=200)),
                ('data_publikacji', models.DateTimeField(verbose_name='Data publikacji')),
            ],
        ),
        migrations.AddField(
            model_name='odpowiedz',
            name='pytanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankieta.Pytanie'),
        ),
    ]
