# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-04 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytanie',
            name='data_publikacji',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 4, 20, 34, 10, 683843, tzinfo=utc), verbose_name='Data publikacji'),
        ),
    ]
